model = "gpt-5.6-terra"
model_reasoning_effort = "medium"
personality = "pragmatic"

[tui]
vim_mode_default = true

[marketplaces.claude-plugins-official]
last_updated = "2026-07-28T23:32:04Z"
last_revision = "da4ce626c8d980d2fd15cc270b78765485ec708a"
source_type = "git"
source = "https://github.com/anthropics/claude-plugins-official.git"

[marketplaces.supabase-agent-skills]
last_updated = "2026-07-28T17:15:41Z"
last_revision = "1ad9aaeb49caafd9e95c0a91116f71890eebbc53"
source_type = "git"
source = "https://github.com/supabase/agent-skills.git"

[plugins."visualize@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."pdf@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."code-review@claude-plugins-official"]
enabled = true

[plugins."code-simplifier@claude-plugins-official"]
enabled = true

[plugins."feature-dev@claude-plugins-official"]
enabled = true

[plugins."frontend-design@claude-plugins-official"]
enabled = true

[plugins."lua-lsp@claude-plugins-official"]
enabled = true

[plugins."playwright@claude-plugins-official"]
enabled = true

[plugins."swift-lsp@claude-plugins-official"]
enabled = true

[plugins."typescript-lsp@claude-plugins-official"]
enabled = true

[plugins."postgres-best-practices@supabase-agent-skills"]
enabled = true

[features]
js_repl = false

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = true

[mcp_servers.github]
url = "https://api.githubcopilot.com/mcp"

[mcp_servers.github.http_headers]
Authorization = "Bearer $GITHUB_MCP_PAT"

[projects."/Users/danny/Desktop/Work/vibes/trackmate"]
trust_level = "trusted"

[projects."/Users/danny/dotfiles"]
trust_level = "trusted"

[hooks.state]

[hooks.state."/Users/danny/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:e6df673f62c47c4546f8416d8b0fec47dc7648cebe6d51b865e64d26162421d4"
enabled = true

[hooks.state."/Users/danny/dotfiles/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:e6df673f62c47c4546f8416d8b0fec47dc7648cebe6d51b865e64d26162421d4"
